# Библиотека Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/artemnikolaev/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

## Создание массивов

In [6]:
np.array([1,2,3,4,5]) + np.array([1,2,3,4,5])

array([ 2,  4,  6,  8, 10])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10, dtype = str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [11]:
np.full(10, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
a = np.zeros(10)

In [13]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [14]:
for xi in a:
    print(xi)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [15]:
arr = np.array([1,2,3,4])

In [16]:
arr

array([1, 2, 3, 4])

In [17]:
arr[3] = 10
arr

array([ 1,  2,  3, 10])

In [19]:
np.arange(10, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
np.arange(0,4,1)

array([0, 1, 2, 3])

In [22]:
np.arange(0,4,3)

array([0, 3])

In [24]:
np.linspace(0, 10 ,11, endpoint=False)

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

In [26]:
np.logspace(0,3,5)# 10^0 10^3

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

### Срезы

In [27]:
arr = np.arange(-1,10)
arr

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [28]:
# элемент с индексом 1
arr[1]

0

In [29]:
# все элементы начиная с индекса 1 и до индекса 5 включительно
arr[1:6]

array([0, 1, 2, 3, 4])

In [30]:
# все элементы начиная с индекса 1
arr[1:11]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# или
arr[1:] # можем написать так, как как хотим получить все до конца

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## размерность 2+

In [36]:
type((1,2)) #tupple

tuple

In [39]:
np.zeros((2,5)) # 2 - строки и 5 столбцов

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
ones = np.ones((3,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
ones[2,2]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [ ]:
np.ones((2,3,4))

In [ ]:
np.full((1,2,3), 2.5)

In [43]:
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [44]:
matrix = np.array([[1,2,3],[4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
matrix[0]# получим первую строку

array([1, 2, 3])

In [46]:
matrix[0][1] # второй элемент первой строки

2

In [47]:
# можно иначе
matrix[0,1]

2

In [48]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# можно делать срезы
matrix[1][1:]

array([5, 6])

In [50]:
# или 
matrix[1, 1:]

array([5, 6])

In [51]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
# можно получить столбец
matrix[:, 1]

array([2, 5])

In [53]:
#можно получить все столбцы
for i in range(len(matrix[0])):
    print('Столбец ' + str(i) + ':',matrix[:, i])

Столбец 0: [1 4]
Столбец 1: [2 5]
Столбец 2: [3 6]


In [65]:
#np.random.seed(2)
np.random.rand(2,2) # генерируем массив любой размерности состоящих из случайных чисел

array([[0.41663394, 0.12787903],
       [0.08091197, 0.11836741]])

## Операции

### Сложение

In [66]:
arr1 = np.random.rand(3)
arr2 = np.random.rand(3)

In [67]:
arr1

array([0.62914245, 0.39449887, 0.38045276])

In [68]:
arr2

array([0.54434384, 0.21192012, 0.37617162])

In [69]:
arr1 + arr2 # склаываются элементы с одинаковыми индексами

array([1.17348628, 0.60641899, 0.75662438])

In [70]:
# добавить элемент к массиву
arr1 + 1 # к какждому элементу добавиться число 1

array([1.62914245, 1.39449887, 1.38045276])

In [71]:
1 + arr1

array([1.62914245, 1.39449887, 1.38045276])

### Вычитание

In [72]:
arr1 = np.random.rand(3)
arr2 = np.random.rand(3)
print(arr2)
print(arr1)
arr2-arr1

[0.01931785 0.00352488 0.00136911]
[0.41499359 0.56972821 0.00288344]


array([-0.39567574, -0.56620334, -0.00151433])

In [73]:
arr1 - 1.1

array([-0.68500641, -0.53027179, -1.09711656])

In [74]:
2.2 - arr2

array([2.18068215, 2.19647512, 2.19863089])

### Умножение

In [75]:
arr1 = np.random.rand(3)
arr2 = np.random.rand(3)
print(arr1)
print(arr2)
arr1*arr2 # умножение происходит поэлементно

[0.83126703 0.73261602 0.25514753]
[0.01279349 0.4466166  0.15106969]


array([0.01063481, 0.32719848, 0.03854506])

In [76]:
# так же массив можно умножить на число
2 * np.array([1,2]) # левое умножение

array([2, 4])

In [77]:
# умножение справа
np.array([2, 3]) * 2  

array([4, 6])

### Деление

In [78]:
arr1 = np.random.rand(3)
arr2 = np.random.rand(3)
print(arr1)
print(arr2)
arr1/arr2

[0.11915994 0.38358972 0.31665773]
[0.36542283 0.34433423 0.2832738 ]


array([0.32608782, 1.11400402, 1.11785039])

In [79]:
arr2/10.0 # деление на число

array([0.03654228, 0.03443342, 0.02832738])

#### Можно ли так?

In [82]:
[1,2] / 10

TypeError: unsupported operand type(s) for /: 'list' and 'int'

## Операции сравнения

In [83]:
a = np.array([2, 3, 5, 7, 11, 13, 17])

In [89]:
true_false = a > 5

In [90]:
a[true_false]

array([ 7, 11, 13, 17])

In [ ]:
a[a > 5]

In [93]:
b = np.array([1,4,6,8,10,10,14])

In [94]:
a>b

array([ True, False, False, False,  True,  True,  True])

In [96]:
a

array([ 2,  3,  5,  7, 11, 13, 17])

In [97]:
b

array([ 1,  4,  6,  8, 10, 10, 14])

In [95]:
a[a>b]

array([ 2, 11, 13, 17])

In [98]:
b[a>b]

array([ 1, 10, 10, 14])

In [101]:
a[[1,1, 1,2]]

array([3, 3, 3, 5])

In [102]:
a[[1,1,1,1,2,2,2]] # взять четыре раза элемент с индексом 1 и 3 раза с индексом 2

array([3, 3, 3, 3, 5, 5, 5])

In [103]:
ab = np.zeros((2,2))

In [104]:
ab[1,1]=1

In [105]:
ab

array([[0., 0.],
       [0., 1.]])

In [106]:
ab[[0,1,0,1]] # берём строки

array([[0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 1.]])

## среднее, станадртное отклонение, сумма

In [107]:
a = np.array([2, 3, 5, 7, 11, 13, 17])

In [108]:
a.mean() # среднее

8.285714285714286

In [109]:
a.sum()

58

In [110]:
a.std()

5.146823867043378

In [111]:
a.min()

2

In [112]:
a.max()

17

## Размерности

In [113]:
a

array([ 2,  3,  5,  7, 11, 13, 17])

In [114]:
a.shape

(7,)

In [115]:
ab = np.zeros((2,7))

In [122]:
ab.shape
#ab.shape[0] - количество строк
#ab.shape[1] - количество столбцов

(2, 7)

## Перемножение матриц и матрицы с вектором

In [123]:
v = np.array([1,2,1,0])
u = np.array([2,3,1,1])

In [125]:
(u*v).sum()

9

In [127]:
u.shape[0]

4

In [128]:
# перемножение векторов
def vector_vector_mult(u,v):
    res = 0
    for i in range(u.shape[0]):
        #print(u[i], v[i])
        res += u[i] * v[i]
    return res

In [129]:
vector_vector_mult(u, v)

9

In [130]:
(u*v).sum() # иначе

9

In [131]:
u.dot(v) # иначе

9

In [132]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [133]:
U.shape

(3, 4)

In [134]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [135]:
V.shape 

(4, 3)

In [139]:
v

array([1, 2, 1, 0])

In [137]:
U.dot(v) # перемножение матрицы на вектор

array([15,  6,  7])

In [136]:
U.dot(V) # перемножение матриц

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Единичная матрица

In [144]:
I = np.eye(3)

In [145]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [147]:
V.shape

(4, 3)

In [148]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Обратная матрица

In [149]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [150]:
Vs = V[[1,2,3]]

In [151]:
Vs

array([[0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [152]:
Vs_inv = np.linalg.inv(Vs)

In [153]:
Vs_inv

array([[ 0.33333333, -0.33333333,  0.5       ],
       [-0.66666667,  0.66666667,  0.        ],
       [ 1.33333333, -0.33333333,  0.        ]])

In [154]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Транспонирование

In [155]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [158]:
V.T.T.T.T.T

array([[1. , 0. , 0. , 2. ],
       [1. , 0.5, 2. , 1. ],
       [2. , 1. , 1. , 0. ]])

In [164]:
np.ones((1,3))

array([[1., 1., 1.]])

In [165]:
np.ones((1,3)).T

array([[1.],
       [1.],
       [1.]])

In [159]:
np.ones(3).T.shape

(3,)

## Решение системы

In [166]:
np.linalg.solve(np.eye(3),np.array([1,2,3]))

array([1., 2., 3.])

## Изменение размерности

In [170]:
zeros = np.arange(12)

In [171]:
zeros

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [172]:
zeros.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
A = np.array([[1,2,3], [3,4,5]])

In [174]:
A

array([[1, 2, 3],
       [3, 4, 5]])

In [175]:
A.reshape((6))

array([1, 2, 3, 3, 4, 5])

In [176]:
A.reshape((6,1))

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5]])

In [179]:
A.reshape((3,2))

array([[1, 2],
       [3, 3],
       [4, 5]])

In [180]:
6.

6.0

# Pandas

In [181]:
import pandas as pd

In [182]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [185]:
pd.DataFrame(data, columns=columns)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [186]:
df = pd.DataFrame(data, columns=columns)

In [187]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [190]:
df.head(2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [191]:
df.head(2).T

0          1
Make               Nissan    Hyundai
Model              Stanza     Sonata
Year                 1991       2017
Engine HP           138.0        NaN
Engine Cylinders        4          4
Transmission Type  MANUAL  AUTOMATIC
Vehicle_Style       sedan      Sedan
MSRP                 2000      27150

## Словарь

In [192]:
a = dict()
b = {}

In [193]:
type(a), type(b)

(dict, dict)

In [194]:
a['hello'] = 5
a['bingo'] = 5
a['cat'] = 3

In [195]:
a

{'hello': 5, 'bingo': 5, 'cat': 3}

In [196]:
a['hello']

5

In [197]:
a = {'hello': 5, 'bingo': 5, 'cat': 3}

In [198]:
a

{'hello': 5, 'bingo': 5, 'cat': 3}

In [199]:
b = {'hello': 10, 'bingo': 10, 'cat': 6}

In [200]:
b['hello']

10

In [202]:
for key in a.keys():
    print(key)

hello
bingo
cat


In [203]:
a.values()

dict_values([5, 5, 3])

In [210]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [211]:
df = pd.DataFrame(data)

In [212]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [215]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340}]

In [216]:
df.head().T

0          1            2          3         4
Make               Nissan    Hyundai        Lotus        GMC    Nissan
Model              Stanza     Sonata        Elise     Acadia  Frontier
Year                 1991       2017         2010       2017      2017
Engine HP           138.0        NaN        218.0      194.0     261.0
Engine Cylinders        4          4            4          4         6
Transmission Type  MANUAL  AUTOMATIC       MANUAL  AUTOMATIC    MANUAL
Vehicle_Style       sedan      Sedan  convertible    4dr SUV    Pickup
MSRP                 2000      27150        54990      34450     32340

## Series

In [217]:
df.head(1)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan  Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style  MSRP  
0         sedan  2000

In [222]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [219]:
type(df.Make)

pandas.core.series.Series

In [223]:
df.Engine HP

SyntaxError: invalid syntax (<ipython-input-223-c0bc881c55b7>, line 1)

In [224]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [227]:
df['Engine HP'].values#.dtype

dtype('float64')

In [226]:
type(df['Engine HP'].values)

numpy.ndarray

In [228]:
df['Engine HP'].values + 5

array([143.,  nan, 223., 199., 266.])

In [231]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [232]:
df['Engine HP'] * df['Engine HP']

0    19044.0
1        NaN
2    47524.0
3    37636.0
4    68121.0
Name: Engine HP, dtype: float64

In [233]:
# add new column
df['id'] = [1,2,3,4,5]

In [234]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [235]:
df['id'] = [10, 20, 30, 40, 50]

In [236]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000  10  
1         Sedan  27150  20  
2   convertible  54990  30  
3       4dr SUV  34450  40  
4        Pickup  32340  50

In [237]:
del df['id'] # delete column

In [238]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

## Index

In [239]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [240]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [241]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [242]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [243]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [244]:
df.iloc[[1,2,3]]#get 2,3,4 rows

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   
d      GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450

In [247]:
df.loc[['b','c']]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990

In [248]:
df.reset_index(drop=True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [249]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [250]:
df = df.reset_index(drop = True)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [251]:
df.iloc[1,1]

'Sonata'

In [253]:
df.iloc[[1]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
1         Sedan  27150

In [254]:
type(df.iloc[1])

pandas.core.series.Series

In [ ]:
df

In [ ]:
df.iloc[1,2]

In [ ]:
df.iloc[:,3:4]

## Операции с Series

In [256]:
df[df['Year'] >= 2015]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450  
4        Pickup  32340

In [ ]:
df['Year'].dtype

In [ ]:
df['Year'].astype(int)

In [ ]:
type(df['Year'] >= 2015)

In [ ]:
(df['Year'] >= 2015).astype(int)

In [ ]:
df[df['Year'] >= 2015]

## Фильтрация

In [ ]:
df[df.Year>=2000]

In [ ]:
df[(df['Make'] == 'Nissan') & (df['Year'] >= 2015)]

## Операции со строками

In [ ]:
'Engine HP'.replace(' ', '_')

In [ ]:
df.columns

In [ ]:
df.columns.str.replace(' ', '_')

In [ ]:
df.columns = df.columns.str.replace(' ', '_')

In [ ]:
df.Engine_HP

In [ ]:
df.Make.str.lower()

In [ ]:
df.Make.str.upper()

In [ ]:
df

In [ ]:
df['Vehicle_Style'].str.lower()

In [ ]:
df['Vehicle_Style'].str.lower().str.replace(' ','_')

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
df

In [ ]:
df.describe()

In [ ]:
df.describe().round(2)

In [ ]:
df.nunique()

In [ ]:
df.isnull().sum()

In [ ]:
df.sum()

## Group by

In [ ]:
df

In [ ]:
df.groupby('transmission_type').max()

In [ ]:
df.groupby('transmission_type').sum()

In [ ]:
df.groupby('transmission_type')['engine_hp'].mean()

In [ ]:
df.msrp.values #get numpy array

In [ ]:
df[df.msrp >= 7777]

## Загрузка из csv файла

In [ ]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/AB_NYC_2019.csv"

In [ ]:
#!wget $url

In [ ]:
df = pd.read_csv('AB_NYC_2019.csv')

In [ ]:
df.head(1).T

In [ ]:
df.describe().T.round(2)